steps:
  # 使用 Docker Compose 构建镜像

  # 将 Docker Compose 生成的映像标记为您希望推送到的目的地
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/bionic-store-417406/introduction-project/frontend'
      - '.'

  # 推送 Docker 镜像到容器注册表
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/bionic-store-417406/introduction-project/frontend']

    

  # 在 Cloud Run 上部署服务（Nginx）

  - name: 'docker/compose'
    args:
      - 'up'
      - '-d'
    dir: '.'
    
