version: '3.1'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    image: asia-east1-docker.pkg.dev/bionic-store-417406/introduction-project/frontend
    restart: always
    ports:
      - "5000:80"