version: '3.8'
services:
  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: .
      args:
        - NODE_VERSION=18
    ports:
      - '3000:3000'

  nginx:
    container_name: nginx
    restart: on-failure
    build: ./nginx
    ports:
      - '80:80'