apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: self-introduction-demo
serialPipeline:
  stages:
  - targetId: self-introduction-demo-target-1
    profiles:
    - target-1