apiVersion: skaffold/v4beta7
kind: Config
metadata: 
  name: deploy-run-quickstart
build:
  tagPolicy:
    gitCommit: {}
  local: {}
profiles:
- name: prod
  manifests:
    rawYaml:
    - ./kubernetes/*
deploy:
  kubectl: {}
  logs:
    prefix: container
  # cloudrun:
  #   projectid: bionic-store-417406
  #   region: asia-east1