apiVersion: apps/v1
kind: Deployment
metadata:
  name: introduciton
spec:
  replicas: 3
  selector:
    matchLabels:
      app: introduciton
  template:
    metadata:
      labels:
        app: introduciton
    spec:
      containers:
        - name: my-container
          image: asia-east1-docker.pkg.dev/bionic-store-417406/introduction-project/frontend
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: introduciton
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer